filebeat.prospectors:
- type: docker
  containers.ids:
   - '36dcedef08af*'
   - '050e45376cf5*'
   - '0bd66a0441a9*'
  processors:
    - add_docker_metadata: ~
  multiline:
    pattern: "^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}"
    negate: true
    match: after
output.logstash:
  hosts: ["logstash:5044"]
  index: filebeat